export const jobListings = [
  {
    title: "Product Designer",
    company: "Microsoft",
    description:
      "Design user-friendly interfaces and improve product usability.",
    jobType: "Part-time",
    level: "Junior level",
    location: "Distant",
    rate: "$200/hr",
    city: "Redmond, WA",
    employmentType: "Contract",
  },
  {
    title: "Frontend Developer",
    company: "Meta",
    description: "Develop and maintain the frontend of web applications.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Shift work",
    rate: "$180/hr",
    city: "San Francisco, CA",
    employmentType: "Full-time",
  },
  {
    title: "UI/UX Designer",
    company: "Adobe",
    description:
      "Create engaging user interfaces and enhance the user experience.",
    jobType: "Project work",
    level: "Middle level",
    location: "Full day",
    rate: "$150/hr",
    city: "Los Angeles, CA",
    employmentType: "Contract",
  },
  {
    title: "Content Strategist",
    company: "Twitter",
    description: "Develop content strategies that align with business goals.",
    jobType: "Part-time",
    level: "Senior level",
    location: "Distant",
    rate: "$120/hr",
    city: "Remote",
    employmentType: "Part-time",
  },
  {
    title: "Graphic Designer",
    company: "Airbnb",
    description: "Design graphics for marketing and branding purposes.",
    jobType: "Project work",
    level: "Junior level",
    location: "Flexible schedule",
    rate: "$90/hr",
    city: "Austin, TX",
    employmentType: "Contract",
  },
  {
    title: "Backend Developer",
    company: "Google",
    description:
      "Develop server-side logic and manage databases for applications.",
    jobType: "Full-time",
    level: "Middle level",
    location: "Full day",
    rate: "$220/hr",
    city: "Mountain View, CA",
    employmentType: "Full-time",
  },
  {
    title: "Data Analyst",
    company: "Netflix",
    description:
      "Analyze data and generate insights to improve business performance.",
    jobType: "Part-time",
    level: "Middle level",
    location: "Distant",
    rate: "$130/hr",
    city: "Los Angeles, CA",
    employmentType: "Part-time",
  },
  {
    title: "Software Engineer",
    company: "Amazon",
    description: "Develop software solutions and improve system performance.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$250/hr",
    city: "Seattle, WA",
    employmentType: "Full-time",
  },
  {
    title: "Marketing Specialist",
    company: "Spotify",
    description:
      "Develop and execute marketing campaigns to boost user engagement.",
    jobType: "Project work",
    level: "Middle level",
    location: "Flexible schedule",
    rate: "$160/hr",
    city: "New York, NY",
    employmentType: "Contract",
  },
  {
    title: "Web Designer",
    company: "LinkedIn",
    description: "Create visually appealing and functional web designs.",
    jobType: "Part-time",
    level: "Junior level",
    location: "Shift work",
    rate: "$110/hr",
    city: "San Francisco, CA",
    employmentType: "Part-time",
  },
  {
    title: "Machine Learning Engineer",
    company: "Tesla",
    description:
      "Develop machine learning models to improve autonomous driving.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$300/hr",
    city: "Palo Alto, CA",
    employmentType: "Full-time",
  },
  {
    title: "Social Media Manager",
    company: "Facebook",
    description: "Manage social media channels and grow audience engagement.",
    jobType: "Project work",
    level: "Middle level",
    location: "Distant",
    rate: "$140/hr",
    city: "Remote",
    employmentType: "Contract",
  },
  {
    title: "Data Scientist",
    company: "Apple",
    description: "Analyze complex datasets to extract actionable insights.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$280/hr",
    city: "Cupertino, CA",
    employmentType: "Full-time",
  },
  {
    title: "Business Analyst",
    company: "Dell",
    description: "Analyze business processes and suggest improvements.",
    jobType: "Part-time",
    level: "Middle level",
    location: "Flexible schedule",
    rate: "$125/hr",
    city: "Austin, TX",
    employmentType: "Part-time",
  },
  {
    title: "DevOps Engineer",
    company: "Cisco",
    description:
      "Build and maintain CI/CD pipelines for deployment automation.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$210/hr",
    city: "San Jose, CA",
    employmentType: "Full-time",
  },
  {
    title: "Project Manager",
    company: "IBM",
    description: "Oversee project timelines and manage resources effectively.",
    jobType: "Project work",
    level: "Senior level",
    location: "Flexible schedule",
    rate: "$190/hr",
    city: "Remote",
    employmentType: "Contract",
  },
  {
    title: "HR Specialist",
    company: "Oracle",
    description: "Manage recruitment processes and employee relations.",
    jobType: "Part-time",
    level: "Junior level",
    location: "Distant",
    rate: "$80/hr",
    city: "Austin, TX",
    employmentType: "Part-time",
  },
  {
    title: "Data Engineer",
    company: "Intel",
    description: "Develop and maintain data pipelines for data processing.",
    jobType: "Full-time",
    level: "Middle level",
    location: "Full day",
    rate: "$180/hr",
    city: "Santa Clara, CA",
    employmentType: "Full-time",
  },
  {
    title: "Product Manager",
    company: "Zoom",
    description: "Define product strategy and lead development cycles.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$270/hr",
    city: "San Jose, CA",
    employmentType: "Full-time",
  },
  {
    title: "Operations Analyst",
    company: "Uber",
    description: "Analyze operations and identify areas for improvement.",
    jobType: "Project work",
    level: "Middle level",
    location: "Flexible schedule",
    rate: "$115/hr",
    city: "San Francisco, CA",
    employmentType: "Contract",
  },
  {
    title: "Full Stack Developer",
    company: "Stripe",
    description:
      "Develop and maintain both front-end and back-end applications.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$240/hr",
    city: "San Francisco, CA",
    employmentType: "Full-time",
  },
  {
    title: "Copywriter",
    company: "Slack",
    description: "Write engaging copy for marketing and communications.",
    jobType: "Part-time",
    level: "Middle level",
    location: "Distant",
    rate: "$90/hr",
    city: "Remote",
    employmentType: "Part-time",
  },
  {
    title: "Graphic Illustrator",
    company: "Etsy",
    description: "Create illustrations for digital and print marketing.",
    jobType: "Project work",
    level: "Junior level",
    location: "Flexible schedule",
    rate: "$75/hr",
    city: "Brooklyn, NY",
    employmentType: "Contract",
  },
  {
    title: "Sales Consultant",
    company: "Zendesk",
    description: "Drive sales growth by managing client relationships.",
    jobType: "Full-time",
    level: "Middle level",
    location: "Full day",
    rate: "$130/hr",
    city: "San Francisco, CA",
    employmentType: "Full-time",
  },
  {
    title: "Research Scientist",
    company: "DeepMind",
    description:
      "Conduct research in artificial intelligence and machine learning.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Distant",
    rate: "$350/hr",
    city: "London, UK",
    employmentType: "Full-time",
  },
  {
    title: "Cybersecurity Analyst",
    company: "FireEye",
    description:
      "Monitor systems for security breaches and protect against attacks.",
    jobType: "Project work",
    level: "Middle level",
    location: "Shift work",
    rate: "$200/hr",
    city: "Washington, DC",
    employmentType: "Contract",
  },
  {
    title: "Account Manager",
    company: "Salesforce",
    description: "Manage client accounts and ensure customer satisfaction.",
    jobType: "Full-time",
    level: "Senior level",
    location: "Full day",
    rate: "$210/hr",
    city: "San Francisco, CA",
    employmentType: "Full-time",
  },
  {
    title: "Technical Writer",
    company: "Atlassian",
    description: "Write technical documentation for products and tools.",
    jobType: "Part-time",
    level: "Junior level",
    location: "Flexible schedule",
    rate: "$100/hr",
    city: "Sydney, Australia",
    employmentType: "Part-time",
  },
  {
    title: "Video Editor",
    company: "YouTube",
    description: "Edit video content for marketing and social media.",
    jobType: "Project work",
    level: "Middle level",
    location: "Distant",
    rate: "$85/hr",
    city: "Remote",
    employmentType: "Contract",
  },
  {
    title: "Customer Success Manager",
    company: "Zendesk",
    description:
      "Assist clients in using products effectively and achieving success.",
    jobType: "Full-time",
    level: "Middle level",
    location: "Full day",
    rate: "$150/hr",
    city: "San Francisco, CA",
    employmentType: "Full-time",
  },
];
